In [70]:
import numpy as np


## The Basics

In [4]:
a= np.array([1,2,3,4,5], dtype ='int32')
print(a)

[1 2 3 4 5]


In [5]:
b = np.array([[7.0,8.0,9.0], [6.0,5.0,4.0]])
print(b)

[[7. 8. 9.]
 [6. 5. 4.]]


In [6]:
#To get dimension
a.ndim

1

In [7]:
#Get shape

b.shape

(2, 3)

In [8]:
#get type
a.dtype

dtype('int32')

In [9]:
#Get size
a.itemsize

4

In [10]:
#Get total size
a.nbytes

20

In [11]:
#get number of elements
a.size

5

# Accessing/Changing specific elements, rows, columns etc

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
#get specific element [r,c]
a[1,5]

13

In [14]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [16]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]
#in the first row, from first column to the last column of that row 
    #with a gap of 2

array([2, 4, 6])

In [17]:
a[1,5] = 20  #changing 13 to 20

a[:,2] = [1,2] #in the second column, change the rows to 1,2
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3-D example

In [18]:
b = np.array([[[2,3],[3,4]],[[5,6],[7,8]]])
print(b)

[[[2 3]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
#Get specific element (work outside in)
b[0,1,1]

4

In [23]:
#replace
b[:,1,:] = [[9,9,9],[8,8]]
#we see error caz we don't have enough cells.

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [26]:
b[:,1,:] = [[9,9],[8,8]]

print(b)

[[[2 3]
  [9 9]]

 [[5 6]
  [8 8]]]


## initializg different types of arrays

In [28]:
#all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
#Similarly all 1s matrix, 
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [32]:
#Any other number 
np.full((2,2) , 99)

array([[99, 99],
       [99, 99]])

In [36]:
#any other number (full_like)
np.full_like(a, 4)
#Return a full array with the same shape and type as a given array
#a = shape and data-type of a define these same attributes of the returned array.
## a is already defined numpy array

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [37]:
#Random decimal numbers
np.random.rand(4,2)



array([[0.10676368, 0.51630789],
       [0.49471591, 0.13257493],
       [0.54847287, 0.91770997],
       [0.05821035, 0.73580795]])

In [38]:
#random integer values
np.random.randint(-4, 8, size = (3,3))
#random integers between -4 and 8 and a table of 3,3 matrix

array([[ 2,  7,  3],
       [ 0,  1,  3],
       [-3,  1,  6]])

In [39]:
#the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
#To repeat an array
arr= np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)
print(arr)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 2 3]]


#### be careful when copying arrays!!!


In [43]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)

[100   2   3]


In [44]:
print(a)

[100   2   3]


In [46]:
#numpy is using a and b to point at the same exact array
#use copy() funtion
b = a.copy()
b[0] = 125
print(a)
#no change in a as b is assigned new array


[100   2   3]


## maths


In [47]:
a= np.array([1,2,4,5])


In [48]:
a +2
#similarly -, x, /,** will act same way


array([3, 4, 6, 7])

In [49]:
b = np.array([1,0,1,0])
a+b


array([2, 2, 5, 5])

In [51]:

#take the sin and cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.65364362,  0.28366219])

In [52]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

## Reorganize=ing arrays


In [55]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape(8,1) #as long as it has same amount of values, like 4,2
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [56]:
#vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [64]:
#horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))


np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## LOAD DATA FROM FILE

In [74]:
#loading a data.txt file from same folder
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata
#it's in float type automatically

array([[1., 2., 3., 4., 5., 6., 7., 8.],
       [4., 2., 3., 5., 6., 2., 3., 4.],
       [4., 2., 3., 5., 7., 4., 2., 1.]])

In [75]:
filedata.astype('int32')

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [4, 2, 3, 5, 6, 2, 3, 4],
       [4, 2, 3, 5, 7, 4, 2, 1]])

##### Boolean masking and advanced indexing

In [77]:
filedata>5

array([[False, False, False, False, False,  True,  True,  True],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False,  True, False, False, False]])

In [79]:
filedata[filedata>4]
#will give us a filedata values where filedata values are bigger than 4

array([5., 6., 7., 8., 5., 6., 5., 7.])

In [81]:
np.any(filedata>4, axis=0)

array([False, False, False,  True,  True,  True,  True,  True])

In [83]:
#numpy. any() returns True if at least one element in a NumPy array evaluates to True while 
#numpy. all() returns True only if all elements in a NumPy array evaluate to True .
((filedata > 3) & (filedata<5))
#This shall return filedata values where they are 4

array([[False, False, False,  True, False, False, False, False],
       [ True, False, False, False, False, False, False,  True],
       [ True, False, False, False, False,  True, False, False]])