In [1]:
import numpy as np
import matplotlib 

In [2]:
#Numpy needs homogeneous array
"""NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes."""


'NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.'

ndarray.ndim
the number of axes (dimensions) of the array.

ndarray.shape
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

ndarray.size
the total number of elements of the array. This is equal to the product of the elements of shape.

ndarray.dtype
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

ndarray.itemsize
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

ndarray.data
the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [3]:
#to create a numpy array
a = np.array([1,3,4,5])
b = [3,5,6,3]
bb = np.array(b)

In [4]:
#To create numpy arrays of zeroes
c = np.zeros(4)
#to create arrays filled with ones
d = np.ones(5)

In [5]:
#The function empty creates an array whose initial content is random and depends on the state of the memory.
#The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!
e = np.empty(5)
print(e)

[2.12199579e-314 2.22524532e-307 5.21733322e-321 6.95208261e-310
 4.89541034e-307]


In [6]:
#an array with a range of elements
f = np.arange(5)
?np.arange

In [7]:
#to create an array with values that are spaced linearly in a specific interval
np.linspace(0, 10, num=5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
#while the default type is floating point (np.float64)
#we can explicitly specify  which data type we want using the dtype keyword
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [9]:
#TO ADD, REMOVE, and SORT elements
arr = np.sort([2,5,24,6,3,26,7,2])

#OR 
arr = [3,5,13,13,5,6,3,23,4]
np.sort(arr)

array([ 3,  3,  4,  5,  5,  6, 13, 13, 23])